name: mbtools_display
description: "mbtools sample"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # librairie ricochets.dev
  mbtools:
    path: ../

  # librairie ricochets.dev
  mbnotificationtools:
    git:
      url: https://github.com/mickbad/flutter_mbnotificationtools.git
      ref: 1.0.0+2

  # gestion du statemanagement
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
