name: mbtools
description: "Ensemble d'outils dart/flutter."
version: 1.2.15+1
homepage: https://www.ricochets.dev

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # gestion de l'application
  connectivity_plus: ^7.0.0
  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0
  path_provider: ^2.1.5
  markdown: ^7.3.0
  wakelock_plus: ^1.4.0

  # markdown
  # STOPPED : TODO Change this very soon
  flutter_markdown: ^0.7.7+1
  # markdown_widget: ^2.3.2+8

  # gestion des données
  shared_preferences: ^2.5.4
  pref: ^2.8.0
  encrypt: ^5.0.3
  # html: ^0.15.5

  # gestion du tracking
  matomo_tracker: ^6.1.0

  # gestion des widgets
  flutter_animate: ^4.5.2
  motion: ^2.0.1
  glassmorphism_ui: ^0.3.0
  flutter_slidable: ^4.0.3

  # gestion de la fenêtre
  window_manager: ^0.5.1
  another_flushbar: ^1.12.32
  windows_taskbar: ^1.1.2

  # gestion de la sortie de veille
  # working with Windows 10 : https://github.com/bikram0000/flutter_desktop_sleep/issues/3
  flutter_desktop_sleep: ^0.0.2

  # localisation
  intl: any

  # network
  url_launcher: ^6.3.2
  http: ^1.6.0
  fetch_client: ^1.2.0

  # notifications
  toastification: ^3.0.3

  # outils design/utilitaire
  share_plus: ^12.0.1
  file_picker: ^10.3.8
  flutter_file_dialog: ^3.0.3
  slug_it: ^0.0.1
  pasteboard:
    git:
      url: https://github.com/MixinNetwork/flutter-plugins.git
      path: packages/pasteboard

  # gestion des sons
  audioplayers: ^6.5.1
  # just_audio: ^0.9.42
  # just_audio_windows: ^0.2.2
  # just_audio_mpv: ^0.1.7 # TODO : voir https://pub.dev/packages/just_audio_media_kit please !!!!!!

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/audio/app/
    - assets/images/
    - assets/images/notifications/
    
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
